apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: corews
  name: corews
spec:
  replicas: 1
  selector:
    matchLabels:
      service: corews
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: corews
    spec:
      containers:
        - image: jandresh/corews:latest
          name: corews
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /
              name: core-pv
      restartPolicy: Always
      volumes:
        - name: core-pv
          persistentVolumeClaim:
            claimName: core-pv
status: {}
