apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: corews
  name: corews
spec:
  replicas: 1
  selector:
    matchLabels:
      service: corews
  strategy: {}
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: corews
    spec:
      containers:
        - image: jandresh/corews:latest
          name: corews
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
