apiVersion: v1
kind: Service
metadata:
  labels:
    service: corews
  name: corews
spec:
  type: ClusterIP
  ports:
    - name: "5003"
      port: 5000
      targetPort: 5000
  selector:
    service: corews
status: {}
