apiVersion: v1
kind: Service
metadata:
  labels:
    service: dbws
  name: dbws
spec:
  type: LoadBalancer
  ports:
    - name: "5001"
      port: 5000
      targetPort: 5000
  selector:
    service: dbws
status: {}
