apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: adccali
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: adccali
          image: mongo:latest
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-db
      restartPolicy: Always
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-pvc
status: {}
