version: "3.7"
services:
  orchestratorws:
    image: jandresh/orchestratorws:latest
    ports:
      - "5004:5000"
    networks:
      - pipeline
networks:
  pipeline:
    external: true
    name: custompipeline
