version: "3.7"
services:
  corews:
    image: jandresh/corews:latest
    ports:
      - "5003:5000"
    networks:
      - pipeline
    volumes:
      - core-pv:/
networks:
  pipeline:
    external: true
    name: custompipeline
volumes:
  core-pv: null
