apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: adccali
            - name: MYSQL_PASSWORD
              value: adccali
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: adccali
          image: mysql:5.7
          name: mysql
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-db
      restartPolicy: Always
      volumes:
        - name: mysql-db
          persistentVolumeClaim:
            claimName: mysql-pvc
status: {}
