apiVersion: v1
kind: Service
metadata:
  labels:
    service: preprocessingws
  name: preprocessingws
spec:
  type: ClusterIP
  ports:
    - name: "5002"
      port: 5000
      targetPort: 5000
  selector:
    service: preprocessingws
status: {}
