version: "3.7"
services:
  preprocessingws:
    image: jandresh/preprocessingws:latest
    ports:
      - "5002:5000"
    networks:
      - pipeline
networks:
  pipeline:
    external: true
    name: custompipeline
