version: "3.7"
services:
  metapubws:
    container_name: metapubws
    restart: always
    image: jandresh/metapubws:latest
    ports:
      - "5000:5000"
    networks:
      - pipeline
networks:
  pipeline:
    name: custompipeline
    driver: bridge